-- =====================================================
-- 🛠️ REPARACIÓN DE ESQUEMA SUPABASE (TUS AGUACATES)
-- =====================================================
-- Copia y pega este script en el SQL Editor de Supabase
-- para solucionar el Error 500 y activar los nuevos campos.
-- =====================================================

-- 1. Agregar columnas de configuración y metadata
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS available_for TEXT DEFAULT 'both',
ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'unit',
ADD COLUMN IF NOT EXISTS weight DECIMAL(12,2) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS min_quantity INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS is_organic BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS benefits TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS reserved_stock INTEGER DEFAULT 0;

-- 2. Agregar el ID numérico secuencial
-- Si ya existe la columna pero no es identidad, este paso podría variar.
-- Asumimos que no existe o queremos asegurarnos de su presencia.
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS numeric_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 3. Crear índices para optimizar búsquedas
CREATE INDEX IF NOT EXISTS idx_products_numeric_id ON products(numeric_id);
CREATE INDEX IF NOT EXISTS idx_products_available_for ON products(available_for);

-- 4. Comentario final de éxito
COMMENT ON COLUMN products.numeric_id IS 'ID secuencial para visualización administrativa';
COMMENT ON COLUMN products.available_for IS 'Control de visibilidad (shop, business, both)';

SELECT 'Esquema de productos reparado exitosamente' as resultado;
